package Quinoa_2_Doc.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with uuid = '19ac1646-b1ed-4d1f-bed9-a16af3458062' (id = 'Quinoa_2_Doc')
accordingly and delete the patch script.
*/
changeProject("19ac1646-b1ed-4d1f-bed9-a16af3458062") {
    cleanup {
        add {
            artifacts(days = 14)
        }
    }
}
