package Quinoa_2_Doc.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = '7674b556-609f-4375-be3d-45ea9b1f380c' (id = 'Quinoa_2_Doc_Deploy')
accordingly and delete the patch script.
*/
changeBuildType("7674b556-609f-4375-be3d-45ea9b1f380c") {
    dependencies {
        expect("Quinoa_2_Doc_Build_Debug") {
            snapshot {
                runOnSameAgent = true
                onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                artifactRules = "Debug.tgz => NewCoverage"
            }
        }
        update("Quinoa_2_Doc_Build_Debug") {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                artifactRules = "Debug.tgz => NewCoverage"
            }
        }

        expect("Quinoa_2_Doc_Build_Release") {
            snapshot {
                runOnSameAgent = true
                onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                artifactRules = "Release.tgz => NewCoverage"
            }
        }
        update("Quinoa_2_Doc_Build_Release") {
            snapshot {
                onDependencyFailure = FailureAction.FAIL_TO_START
            }

            artifacts {
                artifactRules = "Release.tgz => NewCoverage"
            }
        }

    }
}
