package Quinoa_2_Docker.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = 'da2c6f8c-ebc4-4a09-aa57-8a004eca318f' (id = 'Quinoa_2_Docker_Alpine')
accordingly and delete the patch script.
*/
changeBuildType("da2c6f8c-ebc4-4a09-aa57-8a004eca318f") {
    expectSteps {
    }
    steps {
        check(stepsOrder == arrayListOf<String>()) {
            "Unexpected build steps order: $stepsOrder"
        }
        stepsOrder = arrayListOf("RUNNER_23", "RUNNER_24", "RUNNER_30", "RUNNER_32", "RUNNER_33")
    }
}
